language: r
cache: packages
sudo: false
install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"
r_build_args: --no-multiarch --with-keep.source
r_check_args: --as-cran

after_success:
  - Rscript -e 'library(covr); codecov()'
