language: r
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

r_packages:
  - covr
  - beepr
  - doSNOW
  - foreach

after_success:
  - Rscript -e 'library(covr); codecov()'
